version: '3.1'

services:
  app:
    image: node:carbon
    container_name: gatsby-container
    working_dir: /gatsby-project
    volumes:
      - ./:/gatsby-container
      - ./projects/${GATSBY_PROJECT}:/gatsby-project
    ports:
      - "8000:8000"
    # Use gatsby and workflow tools outside of individual projects.
    command: [ "/bin/sh", "-c", "yarn --cwd /gatsby-container global add gatsby gatsby-cli surge; gatsby develop --host 0.0.0.0 --port 8000"]
    environment:
      - NODE_ENV=development
      - GATSBY_PROJECT=hello-world
